//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huwax.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cari
    {
        public int CariId { get; set; }
        public string TCNo { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string VergiNo { get; set; }
        public string VergiDairesi { get; set; }
        public string Firma { get; set; }
        public string Unvan { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Adres { get; set; }
    }
}
