//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huwax.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public string VehicleName { get; set; }
        public string VehiclePlate { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string Gear { get; set; }
        public string Fuel { get; set; }
        public string Km { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
